server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mine
    username: root
    password: f2013001251
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.mine.alpha.dao
